### ISSUE TITLE
inout-08.png Error en la etiqueta descriptiva del circuito 2

### ISSUE THREAD

**Issue by pablodurcas** [Obijuan/Cuadernos-tecnicos-FPGAs-libres#1]
Creo que en la imagen Cuadernos-tecnicos-FPGAs-libres/wiki/CT3-Pines-ES/inout-08.png existe un error.

En la etiqueta descriptiva del circuito 2

![circuito 2 orig](https://user-images.githubusercontent.com/3917556/114002468-2ed4a380-985d-11eb-8908-cadda71e80a3.jpg)

- Donde pone D13 creo que debe poner D0
- Donde pone LED7 creo que debe poner LED0

**Comment by Obijuan** [comment]
¡Hola Pablo!

Si, es una errata. Muchas gracias por reportarla 😀 Ahora en cuanto pueda la arreglo. Cuando esté lo indicaré en esta issue

**Comment by Obijuan** [comment]
¡Corregido! 😀️
